import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Form from "./components/form";
import SearchComponent from "./components/search";
import SubmissionPage from "./components/submission";
import weDevelop from "../../public/WeDevelopNow_logo.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ activePage, setActivePage }) {
	return (
		<>
			<Head>
				<title>ApprenticeTips</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* <main className="flex justify-center text-[#222222]"> */}
			<div className="flex justify-center my-4 w-max lg:min-w-[30vw] p-4 bg-[#ffffff]">
				{activePage === "Form" && <Form setActivePage={setActivePage} />}
				{activePage === "Thank You!" && <SubmissionPage />}
				{activePage === "Search" && <SearchComponent />}
			</div>
			{/* </main> */}
		</>
	);
}
